Repository proposal-signals/signal-utils, pull requests merged in 2024-07, with the labels that each got.

#73 Return dispose function from batchedEffect()
  src/subtle/batched-effect.ts
  src/subtle/reaction.ts
  tests/subtle/batched-effect.test.ts
Labels: bug, enhancement

#74 Remove use of Proxy in signalFunction()
  src/async-function.ts
Labels: enhancement

#79 sync pnpm config for tools
  package.json
Labels: internal
