Repository proposal-signals/signal-utils, pull requests merged in 2024-04, with the labels that each got.

#2 Fix `@signal` decorator types
  .github/workflows/ci.yml
  src/index.ts
  tests/package.json
  tests/tsconfig.json
Labels: bug

#4 More asserstions to assure that @signal is stable
  pnpm-lock.yaml
  tests/@signal.test.ts
  tests/helpers.ts
  tests/package.json
Labels: internal

#5 New util: `ReactiveObject`
  README.md
  package.json
  pnpm-lock.yaml
  src/object.ts
  tests/@signal.test.ts
  tests/helpers.ts
  tests/object.test.ts
  tests/package.json
  tsconfig.json
  vite.config.ts
Labels: enhancement

#7 Prioritize easy testing, but still have public API checking
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tests-public/babel.config.json
  tests-public/package.json
  tests-public/public-api.test.ts
  tests-public/tsconfig.json
  tests-public/vite.config.ts
Labels: internal

#9 New Util: ReactiveArray
  README.md
  src/-private/util.ts
  src/array.ts
  src/object.ts
  tests/array.test.ts
Labels: enhancement

#10 Fix asset generation
  package.json
  tsconfig.json
  vite.config.ts
Labels: bug

#12 Rename to Signal* instead of Reactive*
  CHANGELOG.md
  README.md
  src/array.ts
  src/object.ts
  tests-public/public-api.test.ts
  tests/array.test.ts
  tests/object.test.ts
Labels: enhancement

#14 Implement SignalAsyncData/load
  README.md
  src/array.ts
  src/async-data.ts
  src/promise.ts
  tests-public/public-api.test.ts
  tests/@signal.test.ts
  tests/array.test.ts
  tests/async-data.test.ts
  tests/helpers.ts
  tests/object.test.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#17 Add utilities for avoiding the new keyword
  README.md
  src/array.ts
  src/object.ts
  tests-public/public-api.test.ts
Labels: enhancement

#19 Signal-based automatic async function
  README.md
  babel.config.json
  package.json
  pnpm-lock.yaml
  src/async-data.ts
  src/async-function.ts
  src/async.ts
  tests-public/package.json
  tests/async-data.test.ts
  tests/async-function.test.ts
  tests/helpers.ts
Labels: enhancement

#22 Impelement Map, WeakMap, Set, WeakSet
  README.md
  src/-private/util.ts
  src/map.ts
  src/set.ts
  src/weak-map.ts
  src/weak-set.ts
  tests/helpers.ts
  tests/map.test.ts
  tests/set.test.ts
  tests/weak-map.test.ts
  tests/weak-set.test.ts
Labels: enhancement

#24 Implement `@cached`
  README.md
  src/cached.ts
  tests/@cached.test.ts
Labels: enhancement

#29 Implement `localCopy()` for use outside of classes
  README.md
  src/local-copy.ts
  tests/local-copy.test.ts
Labels: enhancement

#30 Implement: microtask effect
  src/subtle/microtask-effect.ts
  tests/helpers.ts
  tests/subtle/microtask-effect.test.ts
  vite.config.ts
Labels: enhancement

#33 effect(): Fix bug where the watcher stops watching
  src/subtle/microtask-effect.ts
  tests/subtle/microtask-effect.test.ts
Labels: bug

#34 Test against more environments
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
  tests/weak-map.test.ts
  tests/weak-set.test.ts
Labels: internal

#37 Fix effect hang / OOM issue
  src/subtle/microtask-effect.ts
  tests/subtle/microtask-effect.test.ts
Labels: bug

#39 feat(effect): allow unsubscribe
  src/subtle/microtask-effect.ts
  tests/subtle/microtask-effect.test.ts
Labels: enhancement

#46 Update README.md with install instructions
  README.md
Labels: documentation

#47 deep and `@deepSignal`
  README.md
  src/-private/util.ts
  src/deep.ts
  tests/deep.test.ts
  tests/helpers.ts
  tsconfig.json
Labels: enhancement

#49 Unify `@signal` to work on both accessors and getters
  README.md
  src/async-data.ts
  src/cached.ts
  src/index.ts
  tests/@cached.test.ts
  tests/@signal.test.ts
  tests/deep.test.ts
Labels: enhancement

#51 Update repo url
  package.json
Labels: internal

#53 fix(deps): mark `signal-polyfill` as a peer dependency
  README.md
  package.json
  pnpm-lock.yaml
Labels: enhancement

#54 Pin tooling versions, and upgrade lockfile
  package.json
  pnpm-lock.yaml
Labels: internal

#58 Update the contributing section of the README
  .npmrc
  README.md
Labels: documentation

#56 Implement reactive version of Array.prototype.map
  src/array-map.ts
  tests/array-map.test.ts
Labels: enhancement

#60 Add JSBin link to README
  README.md
Labels: documentation
